### ISSUE TITLE
[Feature] User authentication

### ISSUE THREAD

**Issue by alexaib2002** [alexaib2002/project-dataworks_base#11]
## Description

Users must be able to validate themselves against the local DB before committing any changes or querying any data.

## TODO

- [x] Create a DB table for storing user data.
- [x] Bind the query from `main` process onto the `Login` action button.
- [x] First run on the app should display a user creation dialog.

## Depends

List of issues in which this feature depends (may be empty):

- ...

**Comment by alexaib2002** [comment]
- Basic authentication is implemented in #15 . User creation dialog needs to be added though.

**Comment by alexaib2002** [comment]
First run dialog implemented
