### ISSUE TITLE
[Feature] App use cases definition

### ISSUE THREAD

**Issue by alexaib2002** [alexaib2002/project-dataworks_base#18]
## Description

The final user of the app should be allowed to do the following actions once they log inside the app.

## TODO

- [x] Add new customer
- [x] Add new pet
- [x] Add new stay
- [x] Remove existing customer (without deleting their registry)
- [x] Remove existing pet (without deleting their registry)

## Depends

List of issues in which this feature depends (may be empty):
As the app development evolves, some issues will be linked to this one.

- ...
