### ISSUE TITLE
[Feature] Dynamic fields on registry add dialog

### ISSUE THREAD

**Issue by alexaib2002** [alexaib2002/project-dataworks_base#7]
## Description

Register creation dialog fields should be adapted to reflect the data type inside the DB. There are multiple ways to implement this. As its hasn't been decided yet, this case implementation is considered open for discussion.

What's currently defined is the way fields will be interpreted by the app renderer:

- We will receive all the fields of the object, and their type (password: password field, email: text field, age range: drop-down list...). 
- For each field, create a new element with the appropriate id, hint, type... inside the dialog.

## TODO

- [x] Define the implementation.
- [x] ~(?) Header JSON holding each data structure and its expected~
- [x] ~(?) Header inside the DB holding each data structure fields~
- [x] Implement it!

## Depends

List of issues in which this feature depends (may be empty):

- #5

**Comment by alexaib2002** [comment]
Updated issue tasks. Implementation is defined; the db library's function `getColumns` returns an object containing all info related to each field (such as its type, if its a primary key, required...). This will surely become handy for implementing this issue. 

Only thing left to do is actually start the implementation.

**Comment by alexaib2002** [comment]
Implemented by dd0c0c7eb63733970ce8aedec765c03811f0f7f8
